################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
version: "3.7"

services:
  node-red:
    build:
      context: ./
      dockerfile: Dockerfile
    #image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
#    networks:
#      - playground_default
#      - node-red-net
    volumes:
      - ./data:/data
      #- node-red-data:/data
      
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    volumes:
      - ./data/openapi.yaml:/openapi.yaml
    ports:
      - "8001:8080"
    environment:
      SWAGGER_FILE: /openapi.yaml
    networks:
      - default
#      - playground_default
#      - node-red-net
#volumes:
#  node-red-data:
networks:
  default:
    name: playground_default
    external: true
#networks:
  #playground_default:
  #  node-red-net:
